gui:
  sidePanelWidth: 0.25
  expandFocusedSidePanel: true
  nerdFontsVersion: '3'
  authorColors:
    'Artem Sapegin': 'magenta'
  theme:
    activeBorderColor:
      - magenta
      - bold
    inactiveBorderColor:
      - white
    searchingActiveBorderColor:
      - cyan
      - bold
    optionsTextColor:
      - white
    selectedLineBgColor:
      - '#503a5c' # Use `purpleLighter` color to make it readable
    selectedRangeBgColor:
      - magenta
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    markedBaseCommitBgColor:
      - yellow
    markedBaseCommitFgColor:
      - blue
    unstagedChangesColor:
      - white
    defaultFgColor:
      - default
  showRandomTip: false
  showCommandLog: false
git:
  parseEmoji: true
  commit:
    autoWrapCommitMessage: true
    autoWrapWidth: 72
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  copyToClipboardCmd: 'pbcopy < {{text}}'
  editPreset: 'vscode'
  open: 'open {{filename}}'
